include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= How to configure aliases to assigned resources as {vno-initials}

== Introduction

This section describes how to configure aliases to assigned shared resources as an {vno-initials}.

For more detail of this feature, refer to xref:appendices/features.adoc#_aliases_for_assigned_resources[Aliases for Assigned Resources] section.

In this version of the {app-short-name} the configuration is only available using the
REST APIs.

== How to configure aliases for assigned resources by {app-short-name} REST API

=== Add configuration
To configure aliases for the devices and fibers previously assigned by the {inp-initials}
using the {app-short-name} REST API, the {vno-initials} must execute the following step:

.  Send a POST request to the following URL:
link:https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases[https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases,window=_blank]
+
Body::
The request must contain the following JSON body:
+
[source, json]
----
{
    "vno-aliases": [
        {
            "device-id": "{DeviceId}",
            "alias": "{DeviceIdAlias}"
        },
        {
            "fiber-id": "{FiberId}",
            "alias": "{FiberIdAlias}"
        }
    ]
}
----
* *device-id*: The target of the device intent (olt) to assign the alias.
* *fiber-id*: The target of the fiber intent to assign the alias.
* *alias*:  The alias to be assigned to the device or fiber.
+
Must provide at least one of these identifiers (*device-id* or *fiber-id*) along with the alias you want to assign.
+
For example:: Suppose the token for the {vno-initials} called *{vno-name-example}* is sent and if you want to configure aliases for two assigned device intents
and three assigned fiber intents, the following body must be sent: https://{ip-host-example}/{wnp-ac-context}/assigned-resources/aliases
+
[source, json]
----
{
    "vno-aliases": [
        {
            "device-id": "LS-MF1",
            "alias": "OLT1"
        },
        {
            "fiber-id": "LS-MF1-1-1",
            "alias": "OLT1.Fiber1"
        },
        {
            "device-id": "LS-MF2",
            "alias": "OLT2"
        },
        {
            "fiber-id": "LS-MF2-1-1",
            "alias": "OLT2.Fiber1"
        },
        {
            "fiber-id": "LS-MF2-1-2",
            "alias": "OLT2.Fiber2"
        }
    ]
}
----

[NOTE]
====
The access token of the {vno-initials} user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_WNP_access.adoc#_rest_apis_proxies_and_kafka_brokers[REST APIs, proxies and kafka brokers] section.
====

=== Get configuration
To get aliases of the devices and fibers previously assigned by the {inp-initials}
using the {app-short-name} REST API, the {vno-initials} must execute the following step:

.  Send a GET request to the following URL:
link:https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases?page=<PAGE_NUMBER>&size=<PAGE_SIZE>&include-undefined=<INCLUDE_UNDEFINED>&target=<TARGET>&alias=<ALIAS>&type=<TYPE>[https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases?page=<PAGE_NUMBER>&size=<PAGE_SIZE>&include-undefined=<INCLUDE_UNDEFINED>&target=<TARGET>&alias=<ALIAS>&type=<TYPE>,window=_blank]
+
Body::
The request body must be empty.
+
Query Parameters::
+
* *page (optional)*: It is the integer that indicates the page number. The default is 1.
* *size (optional)*: It is the integer that indicates the page size. The default is 20.
* *include-undefined (optional)*: It is the boolean that indicates if the intents without assigned alias will obtain too. The default is true.
* *target (optional)*: It is the string that identify to the target.
* *alias (optional)*: It is the boolean that identify to the alias.
* *type (optional)*: It is the string that indicates an intent type. Possible values are "device" or "fiber".

+
For example - Example 1:: Suppose the token for the {vno-initials} called *{vno-name-example}* is sent and if you want to get aliases of the fiber type:
https://{ip-host-example}/{wnp-ac-context}/assigned-resources/aliases?type=fiber
+
For example - Example 2:: Suppose the token for the {vno-initials} called *{vno-name-example}* is sent and if you want to get aliases filtering by alias "OLT2":
https://{ip-host-example}/{wnp-ac-context}/assigned-resources/aliases/{vno-identifier-example}?alias=OLT2

[NOTE]
====
The access token of the {vno-initials} user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_WNP_access.adoc#_rest_apis_proxies_and_kafka_brokers[REST APIs, proxies and kafka brokers] section.
====

==== Delete configuration
To delete aliases of the devices and fibers previously assigned by the {inp-initials} using the {app-short-name} REST API, the {vno-initials} must execute the following step:

. Send a DELETE request to the following URL:
link:https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases/[https://{altiplano-host}/{wnp-ac-context}/assigned-resources/aliases,window=_blank]
+
Body::
The request must contain the following JSON body:
+
[source, json]
----
{
    "vno-aliases": [
        {
            "device-id": "{DeviceId}",
            "alias": "{DeviceIdAlias}"
        },
        {
            "fiber-id": "{FiberId}",
            "alias": "{FiberIdAlias}"
        }
    ]
}
----
* *device-id*: The target of the device intent (olt) to assign the alias.
* *fiber-id*: The target of the fiber intent to assign the alias.
* *alias*:  The alias to be assigned to the device or fiber.
+
Must provide at least one of these identifiers (*device-id* or *fiber-id*) along with the alias you want to delete.
+
For example:: Suppose the token for the {vno-initials} called *{vno-name-example}* is sent and if you want to delete assigned aliases of a device intent
and two fiber intents, the following body must be sent: https://{ip-host-example}/{wnp-ac-context}/assigned-resources/aliases
+
[source, json]
----
{
    "vno-aliases": [
        {
            "device-id": "LS-MF1",
            "alias": "OLT1"
        },
        {
            "fiber-id": "LS-MF1-1-1",
            "alias": "OLT1.Fiber1"
        },
        {
            "fiber-id": "LS-MF2-1-2",
            "alias": "OLT2.Fiber2"
        }
    ]
}
----

[NOTE]
====
The access token of the {vno-initials} user must be sent in the request as a Bearer Authorization HTTP Header.
To retrieve a token, follow the steps in the xref:How_to_manage_WNP_access.adoc#_rest_apis_proxies_and_kafka_brokers[REST APIs, proxies and kafka brokers] section.
====

include::ROOT:go-back-component.adoc[Back]