include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= {app-short-name} Exposed Interfaces

When {app-short-name} is successfully installed, the following interfaces are exposed:

== {app-short-name} Web UI (To be included in the next release)

Provides a user-friendly way for operators to define, schedule, and monitor software update campaigns.
It allows users to select target clusters, define software matrices, and view campaign status in real-time.

To access it you must enter the following in a web browser: +
link:https://{altiplano-host}/{wnp-web-context}[https://{altiplano-host}/{accm-web-context},window=_blank]

For example if {main-base-app}’s public IP is {ip-host-example} the {app-short-name} WEB UI is available at: +
https://{ip-host-example}/{wnp-web-context}[https://{ip-host-example}/{wnp-web-context},window=_blank]

If additional IPs/hostnames were configured in chart variable ALTIPLANO_PUBLIC_IP_LIST then
this interface will be accessible also using each of them

== {app-short-name} AC (REST API)

The {app-short-name} AC REST API allows an INP user to configure the {app-short-name} sending HTTP REST REQUEST.
To access it you must use the following URL: +
link:https://{altiplano-host}/{wnp-ac-context}[https://{altiplano-host}/{wnp-ac-context},window=_blank]

For example if {main-base-app}’s public IP is: {ip-host-example} the {app-short-name} AC is available at: +
link:https://{ip-host-example}/{wnp-ac-context}[https://{ip-host-example}/{wnp-ac-context},window=_blank]

If additional IPs/hostnames were configured in chart variable ALTIPLANO_PUBLIC_IP_LIST then
this interface will be accessible also using each of them

== {app-short-name} Proxies

As {app-short-name} acts as a proxy for {main-base-app}’s IBN, PM and alarms interfaces, the next interfaces are exposed:

=== IBN

To use the {app-short-name} interface that acts as a proxy for {main-base-app}’s REST IBN the following URL is exposed: +
link:https://{altiplano-host}/{wnp-ibn-context}[https://{altiplano-host}/{wnp-ibn-context},window=_blank]

For example if {main-base-app}’s public IP is: {ip-host-example} the {app-short-name} IBN Proxy is available at: +
link:https://{ip-host-example}/{wnp-ibn-context}[https://{ip-host-example}/{wnp-ibn-context},window=_blank]

If additional IPs/hostnames were configured in chart variable ALTIPLANO_PUBLIC_IP_LIST then
this interface will be accessible also using each of them

=== PM

To use the {app-short-name} interface that acts as a proxy for {main-base-app}’s REST PM the following URL is exposed: +
link:https://{altiplano-host}/{wnp-pm-context}[https://{altiplano-host}/{wnp-pm-context},window=_blank]

For example if {main-base-app}’s public IP is: {ip-host-example} the {app-short-name} IBN Proxy is available at: +
link:https://{ip-host-example}/{wnp-pm-context}[https://{ip-host-example}/{wnp-pm-context},window=_blank]

If additional IPs/hostnames were configured in chart variable ALTIPLANO_PUBLIC_IP_LIST then
this interface will be accessible also using each of them

=== Alarms

To use the {app-short-name} interface that acts as a proxy for {main-base-app}’s REST Alarms interface the following URL is exposed: +
link:https://{altiplano-host}/{wnp-alarm-context}[https://{altiplano-host}/{wnp-alarm-context},window=_blank]

For example if {main-base-app}’s public IP is: {ip-host-example} the {app-short-name} IBN Proxy is available at: +
link:https://{ip-host-example}/{wnp-alarm-context}[https://{ip-host-example}/{wnp-alarm-context},window=_blank]

If additional IPs/hostnames were configured in chart variable ALTIPLANO_PUBLIC_IP_LIST then
this interface will be accessible also using each of them

== Interfaces, ports and protocols used

The following table describes ports and url exposed by the interfaces listed above:

[width="99%",cols="30%,30%,40%,options="header"]
|===
|*Interface* |*Protocol* |*{app-short-name} Service Port/Altiplano Ingress Port*
|WebUI | HTTPS |  8443 / 443
|Configuration REST API | HTTPS | 8443 / 443
|===

include::ROOT:go-back-component.adoc[Back]
